[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
  "commitizen>=4.16.2",
  "faker>=37.0.0",
  "poethepoet>=0.48.0",
  "polyfactory>=2.21.0",
  "pre-commit>=4.6.0",
  "pytest>=8.3.0",
  "pytest-cov>=6.0.0",
  "pytest-django>=4.10.0",
  "ruff>=0.14.10",
  "ty>=0.0.9"
]

[project]
name = "nutrisho"
version = "0.2.0"
description = "Quick and dirty django prototype"
authors = [{name = "Your Name", email = "you@example.com"}]
license = "0BSD"
requires-python = ">=3.14,<3.15"
dependencies = [
  "Django ~=6.0.0",
  "PyYAML ~=6.0",
  "django-debug-toolbar ~=6.1",
  "django-environ>=0.13.0",
  "django-htmx>=1.27.0",
  "google-genai~=1.56",
  "xmltodict"
]

[tool.coverage.run]
omit = [
  "*/migrations/*",
  "*/settings*.py",
  "*/asgi.py",
  "*/wsgi.py",
  "*/manage.py"
]

[tool.hatch.build.targets.wheel]
packages = ["src/nutrisho", "src/recipes"]

[tool.hatch.build.targets.wheel.sources]
"src" = ""

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "nutrisho.settings.test"
pythonpath = ["src"]
testpaths = ["tests"]

[tool.poe]
include = [".poe.toml"]
