# Generated by Django 6.0.1 on 2026-05-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_recipe_servings"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="yaml_filename",
            field=models.CharField(
                blank=True,
                default="",
                max_length=260,
                verbose_name="source YAML filename",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="quantity as recorded in source",
            ),
        ),
    ]
