# Generated by Django 6.0.1 on 2026-06-12 21:44

import django.db.models.deletion
from django.db import migrations, models


def _null_charfields_to_empty(apps, schema_editor):
    """Backfill NULLs before the columns become NOT NULL."""
    Recipe = apps.get_model("recipes", "Recipe")
    IngredientGroup = apps.get_model("recipes", "IngredientGroup")
    IngredientInRecipe = apps.get_model("recipes", "IngredientInRecipe")
    Recipe.objects.filter(short_description__isnull=True).update(short_description="")
    IngredientGroup.objects.filter(group_name__isnull=True).update(group_name="")
    IngredientInRecipe.objects.filter(unit__isnull=True).update(unit="")
    IngredientInRecipe.objects.filter(preparation__isnull=True).update(preparation="")


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_sanitize_yaml_filenames"),
    ]

    operations = [
        migrations.RunPython(_null_charfields_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="ingredient",
            name="family",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VEG", "Vegetable"),
                    ("MEA", "Meat"),
                    ("SEA", "Seafood"),
                    ("FSH", "Fish"),
                    ("GRA", "Grain"),
                    ("GRN", "Green"),
                    ("SPI", "Spice"),
                    ("CHE", "Cheese"),
                    ("MLK", "Milk product"),
                    ("FAT", "Fat"),
                    ("CND", "Condiment"),
                    ("PUL", "Pulse"),
                    ("NUT", "Nut"),
                    ("SEE", "Seed"),
                    ("FRU", "Fruit"),
                    ("EGG", "Egg"),
                    ("CHM", "Chemical"),
                    ("MSC", "Misc"),
                ],
                max_length=32,
                verbose_name="Broad ingredient category (vegetable, spice, ...)",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientgroup",
            name="group_name",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Label for group"
            ),
        ),
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="recipes.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="preparation",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="chopped, blanched...",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="substitute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="recipes.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="the unit"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="short_description",
            field=models.CharField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="A short blurb about the recipe",
            ),
        ),
    ]
