# Generated by Django 6.0.1 on 2026-06-13 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0010_recipe_owner_cascade_no_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_name",
            field=models.CharField(max_length=200, verbose_name="Recipe main name"),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                fields=("owner", "recipe_name"),
                name="recipes_recipe_unique_name_per_owner",
            ),
        ),
    ]
