# Generated by Django 6.0.8 on 2026-09-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0013_ingredient_ingredient_name_ci_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="plural_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="plural display form; blank derives it from the rule",
            ),
        ),
    ]
