# Generated by Django 6.0.8 on 2026-09-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0014_ingredient_plural_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="step_title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="An optional heading for a step",
            ),
        ),
    ]
