# Generated by Django 4.0.3 on 2022-03-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=200, verbose_name='region.area.subarea just as placeholder')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Recipe main name')),
                ('short_description', models.CharField(max_length=200, null=True, verbose_name='A short blurb about the recipe')),
                ('source', models.CharField(max_length=200, null=True, verbose_name='The URL or book where the recipe came from')),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64, verbose_name='Name of tag')),
                ('recipe', models.ManyToManyField(to='recipes.recipe')),
            ],
        ),
    ]
