# Generated by Django 4.0.3 on 2022-03-24 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=200, unique=True, verbose_name='region.area.subarea just as placeholder')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('dietary_constraint', models.CharField(choices=[('PSC', 'Pescatarian'), ('VGT', 'Vegetarian'), ('VGN', 'Vegan')], max_length=32, null=True, verbose_name='vegetarian etc')),
                ('family', models.CharField(choices=[('VEG', 'Vegetable'), ('MEA', 'Meat'), ('SEA', 'Seafood'), ('FSH', 'Fish'), ('GRA', 'Grain'), ('GRN', 'Green'), ('SPI', 'Spice'), ('CHE', 'Cheese'), ('MLK', 'Milk product'), ('FAT', 'Fat'), ('CND', 'Condiment'), ('PUL', 'Pulse'), ('NUT', 'Nut'), ('SEE', 'Seed'), ('FRU', 'Fruit'), ('EGG', 'Egg'), ('CHM', 'Chemical'), ('MSC', 'Misc')], max_length=32, null=True, verbose_name='Anything that will let you find the source: ISDN, url...')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Label for group')),
                ('index_in_sequence', models.SmallIntegerField(verbose_name='Where to show this group, for a given recipe?')),
            ],
            options={
                'ordering': ['index_in_sequence'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Recipe main name')),
                ('short_description', models.CharField(max_length=200, null=True, verbose_name='A short blurb about the recipe')),
                ('source_instance', models.CharField(max_length=200, null=True, verbose_name='For example, the page if source is a book, or URL if source is a website')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.cuisine')),
                ('owner', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64, unique=True, verbose_name='Name of tag')),
                ('recipe', models.ManyToManyField(blank=True, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=512, verbose_name='The description of a step')),
                ('index_in_sequence', models.SmallIntegerField(verbose_name='What step is this, for a given recipe?')),
                ('duration', models.DurationField(null=True, verbose_name='How long the step should take')),
                ('extra_info', models.CharField(max_length=512, null=True, verbose_name='extra information, for example how to peel tomatoes')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='recipes.recipe')),
            ],
            options={
                'ordering': ['index_in_sequence'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=64, unique=True, verbose_name="A short name like 'Moro book'")),
                ('source', models.CharField(max_length=255, unique=True, verbose_name='Anything that will let you find the source: ISDN, url...')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='recipes.source')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.source'),
        ),
        migrations.CreateModel(
            name='IngredientInRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=32, null=True, verbose_name='the unit')),
                ('preparation', models.CharField(max_length=128, null=True, verbose_name='chopped, blanched...')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='how many')),
                ('index_in_sequence', models.SmallIntegerField(verbose_name='Where to show this ingredient, for a given group?')),
                ('note', models.CharField(max_length=128, null=True, verbose_name='any extra info')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recipes.ingredient')),
                ('ingredient_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.ingredientgroup')),
                ('substitute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recipes.ingredient')),
            ],
            options={
                'ordering': ['index_in_sequence'],
            },
        ),
        migrations.AddField(
            model_name='ingredientgroup',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_group', to='recipes.recipe'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('index_in_sequence', 'recipe'), name='unique Step in sequence'),
        ),
        migrations.AddConstraint(
            model_name='ingredientinrecipe',
            constraint=models.UniqueConstraint(fields=('index_in_sequence', 'ingredient_group', 'ingredient'), name='unique IngredientInRecipe step in sequence'),
        ),
        migrations.AddConstraint(
            model_name='ingredientgroup',
            constraint=models.UniqueConstraint(fields=('index_in_sequence', 'recipe'), name='unique IngredientGroup step in sequence'),
        ),
    ]
